
import React from "react";
import './../styles/App.css';
import AutocompleteCities from "./AutocompleteCities";

const App = () => {
   const indianCities = [
        "Mumbai",
        "Delhi",
        "Bengaluru",
        "Hyderabad",
        "Chennai",
        "Kolkata",
        "Pune",
        "Ahmedabad",
        "Jaipur",
        "Surat",
        "Lucknow",
        "Kanpur",
        "Nagpur",
        "Indore",
        "Thane",
        "Bhopal",
        "Visakhapatnam",
        "Patna",
        "Vadodara",
        "Ghaziabad",
        "Ludhiana",
        "Agra",
        "Nashik",
        "Faridabad",
        "Meerut",
        "Rajkot",
        "Kalyan-Dombivli",
        "Vasai-Virar",
        "Varanasi",
        "Srinagar",
        "Aurangabad",
        "Dhanbad",
        "Amritsar",
        "Navi Mumbai",
        "Allahabad",
        "Ranchi",
        "Howrah",
        "Coimbatore",
        "Jabalpur",
        "Gwalior",
        "Vijayawada",
        "Jodhpur",
        "Madurai",
        "Raipur",
        "Kota",
        "Guwahati",
        "Chandigarh",
        "Solapur",
        "Hubballi-Dharwad",
        "Bareilly",
        "Mysuru",
        "Tiruchirappalli",
        "Salem",
        "Aligarh",
        "Thiruvananthapuram",
        "Moradabad",
        "Jalandhar",
        "Bhubaneswar",
        "Warangal",
        "Guntur",
        "Bhiwandi",
        "Saharanpur",
        "Gorakhpur",
        "Bikaner",
        "Amravati",
        "Noida",
        "Jamshedpur",
        "Bhilai",
        "Cuttack",
        "Firozabad",
        "Kochi",
        "Nellore",
        "Bhavnagar",
        "Dehradun",
        "Durgapur",
        "Asansol",
        "Rourkela",
        "Nanded",
        "Kolhapur",
        "Ajmer",
        "Akola",
        "Gulbarga",
        "Jamnagar",
        "Ujjain",
        "Loni",
        "Siliguri",
        "Jhansi",
        "Ulhasnagar",
        "Jammu",
        "Mangalore",
        "Belgaum",
        "Kurnool",
        "Ambattur",
        "Tirunelveli",
        "Malegaon",
        "Gaya",
        "Udaipur"
    ];
  return (
    <div>
        {/* Do not remove the main div */}
        <AutocompleteCities suggestions={indianCities}/>
    </div>
  )
}

export default App
